/*
 * Symbolic Boilerplate
 *
 * An API spec for managing todo lists
 *
 * API version: 1.0.0
 * Contact: contact@simonball.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todos

import "github.com/uptrace/bun"

type Todo struct {
	bun.BaseModel `bun:"table:todos"`

	Id int64 `json:"id" bun:"id,pk,autoincrement" copier:"must,nopanic"`

	Title string `json:"title" bun:"title" copier:"must"`

	Content string `json:"content" bun:"content" copier:"must"`

	Complete bool `json:"complete" bun:"complete" copier:"must,nopanic"`
}

type TodoListing struct {
	Id float32 `json:"id"`

	Title string `json:"title"`

	Complete bool `json:"complete"`
}
