/*
 * Symbolic Boilerplate
 *
 * An API spec for managing todo lists
 *
 * API version: 1.0.0
 * Contact: contact@simonball.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package todos

type TodosGet200Response struct {
	Message string `json:"message"`

	Data []TodoListing `json:"data"`
}

type TodosGetById200Response struct {
	Message string `json:"message"`

	Data Todo `json:"data"`
}

type TodosPost200Response struct {
	Message string `json:"message"`

	Data Todo `json:"data"`
}

type TodosPutById200Response struct {
	Message string `json:"message"`

	Data Todo `json:"data"`
}
